version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_NAME:-user}
      POSTGRES_PASSWORD: ${DB_NAME:-password}
      POSTGRES_DB: ${DB_NAME:-referral_codes_db_test}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  backend:
#    build: .
##    command: sleep 9000
#    ports:
#      - "8000:8000"
#    depends_on:
#      - db

volumes:
  postgres_data:
